name: Checkoutthe latest addon template

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  checkoutAddonTemplate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        path: main
    - name: checkout template
      uses: actions/checkout@v2
      with:
        repository: nvdaaddons/AddonTemplate
        path: template
    - name: Copy template
      run: cp template/*.* main
