name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Add-on version'
        required: true
        default: '0.0.0'

jobs:
  buildAndUpload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install scons markdown
        sudo apt update
        sudo apt install gettext
    - name: Add add-on version
      run: |
        import re
        with open("buildVars.py", 'r+', encoding='utf-8') as f:
          text = f.read()
          version = "${{ github.event.inputs.version }}"
          text = re.sub(r"\"addon_version\": .*?,", f"\"addon_version\": \"{version}\",", text)
          f.seek(0)
          f.write(text)
          f.truncate()
      shell: python 
    - name: Push changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git commit -a -m "Update buildVars"
        git push origin HEAD:main
    - name: Build add-on
      run: scons
    - name: Calculate sha256
      run: sha256sum *.nvda-addon >> changelog.md
    - name: Create metadata file
      run: |
        import json
        with open("fake.json") as f:
          data = json.load(f)
        with open("changelog.md") as f:
          sha256 = f.readlines()[-1].split()[0]
          data["URL"] = f"https://github.com/nvdaes/cursorLocator/releases/download/{${{ github.event.inputs.version }}}/cursorLocator-{${{ github.event.inputs.version }}}.nvda-addon"
        data["sha256"] = sha256
        with open("${{ github.event.inputs.version }}.json", "w") as f:
          json.dump(data, f, indent="\t")
      shell: python
    - name: Upload metadata
      uses: actions/upload-artifact@v2
      with:
        name: metadata
        path: ${{ github.event.inputs.version }}.json
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        files: |
          *.nvda-addon
          ${{ github.event.inputs.version }}.json
        body_path: changelog.md
        prerelease: ${{ endsWith(github.event.inputs.version, '-dev') }}

  validate:
    runs-on: windows-latest
    needs: buildAndUpload
    steps:
          
    - name: Checkout validate repo
      uses: actions/checkout@v2
      with:
        repository: nvaccess/validateNvdaAddonMetadata
        submodules: true
    - name: Install validateNvdaAddonMetadata dependencies
      run: |
        python -m pip install --upgrade wheel
        pip install -r requirements.txt
    - name: Download metadata
      uses: actions/download-artifact@v2
      with:
        name: metadata
        path: addons/cursorLocator
    - name: Validate metadata
      run: runvalidate "addons/cursorLocator/${{ github.event.inputs.version }}.json"
      shell: cmd
