name: Publish to add-on datastore

on:
  workflow_dispatch:
    inputs:
      downloadUrl:  
        description: 'Add-on download URL'
        required: true
      url:  
        description: 'URL to get info about the add-on'
        required: true
      channel:
        description: 'Add-on channel for store'
        default: stable
        type: choice
        options:
        - stable
        - beta
      license:
        description: 'Add-on license'
        default: 'GPL v2'
      licenseURL:
        description: 'Add-on license URL'
        default: 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.html'

jobs:

  store:
    runs-on: windows-latest
    
    steps:
    - name: Checkout validation repo
      uses: actions/checkout@v3
      with:
        repository: nvaccess/addon-datastore-validation
        submodules: true
        path: validation
    - name: Checkout datastore repo
      uses: actions/checkout@v3
      with:
        repository: nvaccess/addon-datastore
        path: store
    - name: Download add-on
      run: |
        curl --location --output addon.nvda-addon ${{ inputs.url }}
    - name: Create json
      run: |
        validation\runcreatejson -f addon.nvda-addon --dir store\addons --channel=${{ inputs.channel }} --publisher=${{ github.event.sender.login }} --sourceUrl=${{ inputs.url }}/ --url=${{ inputs.downloadUrl }} --licName="${{ inputs.license }}" --licUrl=${{ inputs.licenseURL }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PR_ACCESS_TOKEN }}
        path: store
        commit-message: Add ${{ github.event.repository.name }} ${{ inputs.version }} add-on
        branch: ${{ github.event.repository.name}}-${{ inputs.version }}
        delete-branch: true
        title: Add add-on
        push-to-fork: ${{ github.event.sender.login }}/addon-datastore
